### ISSUE TITLE
ECONNREFUSED whilst shutting down server

### ISSUE THREAD

**Issue by pp-james** [seckardt/grunt-protractor-webdriver#11]
Selenium server runs fine, and all of my tests run without a hitch, however when the server starts to shutdown I get this message:

```
Shut down Selenium server: http://127.0.0.1:4444 (OKOK)

C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdri
ver\http\index.js:145:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
==== async task ====
WebDriver.quit()
    at [object Object].webdriver.WebDriver.schedule (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.quit (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:418:21)
    at C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\lib\driverProviders\driverProvider.js:28:16
    at C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
    at notify (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:465:12)
    at [object Object].then (C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:522:7)
    at C:\dev\sites\myapp\myapp-frontend\node_modules\grunt-protractor-runner\node_modules\protractor\lib\driverProviders\driverProvider.js:26:25
    at Array.map (native)
[launcher] Process exited with error code 1
>>
Fatal error: protractor exited with code: 1
```

**Comment by MrDefinite** [comment]
+1 same problem.
Environment:
"protractor": "^1.5.0",
"grunt-protractor-runner": "^1.1.4",
"jasmine-reporters": "^1.0.1",
"grunt-protractor-webdriver": "^0.2.0"

**Comment by pp-james** [comment]
I should add, I am running Windows, however my colleague running Ubuntu does not get any errors.

**Comment by CThuleHansen** [comment]
I am getting the same issue on windows server 2012. Related SO: http://stackoverflow.com/questions/20055593/unable-to-run-protractor-econnrefused-connect-econnrefused

**Comment by chazzlabs** [comment]
I'm seeing this same issue on Windows 8.1.

```
"grunt-protractor-runner": "~2.0.0",
"grunt-protractor-webdriver": "~0.2.0"
```

Adding 

```
command: 'webdriver-manager start --standalone'
```
per the StackOverflow post referenced above didn't solve this for me.  @pp-james did you ever find a resolution?

**Comment by chazzlabs** [comment]
I'm no longer seeing this error if I add

```
keepAlive: true
```

to my protractor_webdriver options.  This seems like a shaky workaround, however.

**Comment by digita1-Anal0g** [comment]
I, too, am getting this error, but the work around provided by @chazzlabs resolves it.
